### PR TITLE
Datablock Storage: raise StudentFacingError if called without a table_name

### LINKED ISSUE #58591: ActiveRecord::NotNullViolation in datablock_storage # create_record: Mysql2::Error: Field 'table_name' doesn't have a default value
From Honeybadger: https://app.honeybadger.io/projects/3240/faults/107785410

### PR DESCRIPTION
**Pull request by snickell**
I believe this will fixes [#58591](https://github.com/code-dot-org/code-dot-org/issues/58591), which we got from honeybadger.

### CODE REVIEW

File: dashboard/app/controllers/datablock_storage_controller.rb [hunk 1]
```diff
@@ -326,7 +326,11 @@ def use_firebase_storage
   end
 
   private def where_table
-    DatablockStorageTable.where(project_id: @project_id, table_name: params[:table_name])
+    if params[:table_name]
+      DatablockStorageTable.where(project_id: @project_id, table_name: params[:table_name])
+    else
+      raise StudentFacingError, "You must specify a table"
```
Comment (cnbrenci) [inline dashboard/app/controllers/datablock_storage_controller.rb:332]: We should be able to test this in the same test harness thing that we used to test getColumn to make sure that error is being routed all the way to the student console! I will go find after I finish reviewing the others.

Comment (snickell) [reply dashboard/app/controllers/datablock_storage_controller.rb:332]: I mean, we could add a controller test, but I'm pretty 🤷 on that ("tests that don't break aren't good tests"), and we can't do testing that involves crossing the JS <-> backend (we never figured out how to test that).

Comment (cnbrenci) [reply dashboard/app/controllers/datablock_storage_controller.rb:332]: Because when called through the block itself, there's always a table_name sent, yeah? and we just aren't sure how this is getting called without one. is that right?

**Review by cnbrenci — APPROVED** [review]

File: dashboard/app/controllers/datablock_storage_controller.rb (hunk 1 above)
Comment (snickell) [reply dashboard/app/controllers/datablock_storage_controller.rb:332]: yup, that's IT!
